server:
  port: 8090

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins:
                  - "http://localhost:5173"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowedHeaders: "*"
                allowCredentials: true
          routes:
            - id: service-auth
              uri: http://localhost:8081
              predicates:
                - Path=/api/auth/**
            - id: service-learning
              uri: http://localhost:8082
              predicates:
                - Path=/api/learning/**
            - id: service-achievements
              uri: http://localhost:8083
              predicates:
                - Path=/api/achievements/**
            - id: service-clan
              uri: http://localhost:8085
              predicates:
                - Path=/api/clan/**
            - id: service-forum
              uri: http://localhost:8084
              predicates:
                - Path=/api/forum/**

---
spring:
  config:
    activate:
      on-profile: docker
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: service-auth
              uri: http://service-auth:8081
              predicates:
                - Path=/api/auth/**
            - id: service-learning
              uri: http://service-learning:8082
              predicates:
                - Path=/api/learning/**
            - id: service-achievements
              uri: http://service-achievements:8083
              predicates:
                - Path=/api/achievements/**
            - id: service-clan
              uri: http://service-clan:8085
              predicates:
                - Path=/api/clan/**
            - id: service-forum
              uri: http://service-forum:8084
              predicates:
                - Path=/api/forum/**